defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]


[acme]
email = "{email}@{site_name}"
storage = "/etc/traefik/acme.json"
entrypoint = "https"
OnDemand = true

[docker]
domain = "{site_name}"
watch = true
exposedbydefault = false
endpoint = "unix:///var/run/docker.sock"
